### ISSUE TITLE
overlays are not fixed

### ISSUE THREAD

**Issue by kylemcdonald** [obviousjim/ofxOculusDK2#11]
Maybe I'm misunderstanding the idea of an overlay, but shouldn't an overlay appear perfectly fixed?

Yet when you put an overlay up and wiggle the Rift, the overlay wobbles very slightly.

**Comment by kylemcdonald** [comment]
Actually, just noticed this is true for their "Demo Scene" as well. Doesn't make sense to me, but it's not specific to `ofxOculusDK2`

**Comment by obviousjim** [comment]
It's perceptual motion compensation-- I think it's part of predictive
tracking. You definitely don't see it as wrong when you are wearing the
headset.

On Saturday, March 7, 2015, Kyle McDonald notifications@github.com wrote:

> Actually, just noticed this is true for their "Demo Scene" as well.
> Doesn't make sense to me, but it's not specific to ofxOculusDK2
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/obviousjim/ofxOculusDK2/issues/11#issuecomment-77700920
> .

## 
- James

**Comment by kylemcdonald** [comment]
super interesting / weird. going to close this until i understand it better.
